name: Scheduled Azure VM Resize

on:
  schedule:
    - cron: '43 17 * * *'
    - cron: '33 18 * * *'

jobs:
  resize-vms:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: pip install pyyaml

      - name: Set GITHUB_EVENT_SCHEDULE env var
        run: echo "GITHUB_EVENT_SCHEDULE=${{ github.event.schedule }}" >> $GITHUB_ENV

      - name: Run resize.py to update tfvars
        run: python resize.py

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Show only VM size change in the plan for each application
      - name: Show size plan change for each application
        run: |
          for dir in application/*; do
            tfvars=$(ls "$dir"/*.tfvars 2>/dev/null | head -n 1)
            if [ -f "$tfvars" ]; then
              cd $dir
              terraform init
              echo "## Size change in plan for $dir"
              terraform plan -var-file=$(basename $tfvars) -no-color | grep 'size *= ' || echo "No size changes"
              cd ../..
            fi
          done

      - name: Terraform Apply for each application
        run: |
          for dir in application/*; do
            tfvars=$(ls "$dir"/*.tfvars 2>/dev/null | head -n 1)
            if [ -f "$tfvars" ]; then
              cd $dir
              terraform init
              terraform apply -auto-approve -var-file=$(basename $tfvars)
              cd ../..
            fi
          done
        env:
          TF_VAR_azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_azure_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          TF_VAR_azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          TF_VAR_sub1_subscription_id: ${{ secrets.SUB1_SUBSCRIPTION_ID }}
